max_epoch: 2000
embedding_dim: 768
multigpu: False
adam_beta1: 0.9
adam_beta2: 0.999
learning_rate: 0.01
batch_size: 4
max_length: 512
seq_len: 50
end_year: 2015
frequency: 5
stats_dir: 'stats/bert'
data_path: 'data/citation.csv'