max_epoch: 30
bert_cased: True
multigpu: False
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_eps: 0.000001
learning_rate: 0.00005
batch_size: 16
max_length: 128
seq_len: 50
end_year: 2020
frequency: 5
recall_K: [5, 10, 30, 50, 80]
K: 10
stats_dir: 'stats/bert_cased'
data_path: 'data/citation.csv'